### ISSUE TITLE
point to the original repo

### ISSUE THREAD

**Issue by pedro-nonfree** [fgolemo/qemunet#1]
Thanks for doing this repository, I think is in the first position at google looking for qemunet, but please, point to the original repository that seems to be https://gitlab.inria.fr/esnard/qemunet/

and mirror it or archive it...? or this version is interesting for something?

**Comment by fgolemo** [comment]
During the last semester some of my students couldn't access the original repository at gitlab.inria.fr. this seems to be fixed now.
You're correct in that I forgot the link. I'll add that to the readme and then leave this repository as it is just in case there are problems again with the INRIA servers.

**Comment by pedro-nonfree** [comment]
https://github.com/fgolemo/qemunet#attribution

Great text!

Thanks

**Comment by fgolemo** [comment]
Np, thanks for pointing it out. :)
